### ISSUE TITLE
V0.4.1 Info wird dauerhaft beschrieben

### ISSUE THREAD

**Issue by guergen1** [Xenon-s/js.device-reminder#1]
![grafik](https://user-images.githubusercontent.com/34395245/92327921-56f8eb80-f05d-11ea-9326-4700caac5c0d.png)

**Comment by Xenon-s** [comment]
neue Version 0.4.2 auf github verfügbar, danke fürs Feedback

**Comment by guergen1** [comment]
Dafür testen wir doch....

**Comment by guergen1** [comment]
Läuft!
