### ISSUE TITLE
Testgerät frei konfigurieren

### ISSUE THREAD

**Issue by FlUtZ90602** [Xenon-s/js.device-reminder#2]
Im Skript ist bereits die Möglichkeit gegeben, Testgerät zu erstellen. Super wäre, wenn man die Einschalt-, Ausschalt- und Zeitverzögerungswerte im oberen Eingabebereich konfigurieren könnte, damit man nicht erst die entsprechende Zeile ganz weit hinten im Skript suchen muss.

**Comment by Xenon-s** [comment]
sollte mit der neuen readme jetzt erledigt sein
